//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TTB2.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        public int SoPhieuN { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> SoLuongChungTu { get; set; }
        public Nullable<int> SoLuongThucNhap { get; set; }
        public Nullable<int> MaTB { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual THIETBI THIETBI { get; set; }
    }
}
