//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TTB2.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUAT
    {
        public int SoPhieuX { get; set; }
        public string TenPhieuX { get; set; }
        public Nullable<int> MaTB { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
    
        public virtual THIETBI THIETBI { get; set; }
    }
}
