//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TTB2.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGBAN
    {
        public int MaPB { get; set; }
        public string TenPB { get; set; }
        public string TinhTrang { get; set; }
        public string MoTa { get; set; }
    }
}
